#!/bin/sh

# เช็คว่าตอนนี้อยู่ branch อะไร
branch="$(git rev-parse --abbrev-r+620ef HEAD)"

# ถ้าเป็น main ให้ด่าแล้วหยุด push
if [ "$branch" = "main" ]; then
    echo "================================================="
    echo "❌ ไม่อนุญาตให้ PUSH เข้า main โดยตรง!"
    echo "เปิร์น อยากต่อยจริงๆเลยนะเนี่ย 😠"
    echo "กรุณาสร้าง Branch ใหม่ แล้วไปเปิด Pull Request บน GitHub"
    echo "================================================="
    exit 1
fi